name: Update dependencies

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
    - run: nix flake update
    - run: nix flake update
      working-directory: lock
    - run: git diff-index --exit-code --name-status HEAD
      id: diff
    - uses: peter-evans/create-pull-request@v3
      if: ${{ steps.diff.outcome == 'failure' }}
      with:
        commit-message: 'Update dependencies'
        base: master
        title: 'chore: Update dependencies'
        branch: create-pull-request/update
        labels: automation,update
